### POST request to create a new patient
POST http://localhost:4000/patients
Content-Type: application/json

{
  "name": "Pepe with Billing account with Kafka",
  "surname": "",
  "dni": "12345679B",
  "email": "pepe3_billingKafka@email.com",
  "phoneNumber": "+34 958262214",
  "address": "C/ False 123, Munich",
  "birthDate": "1992-09-01",
  "registerDate": "2005-02-03"
}
###